### ISSUE TITLE
Can't properly add a facility named "Viktor is a dingus"

### ISSUE THREAD

**Issue by vr2262** [SEL-Columbia/Revisit-Android#1]
I tried 3 times.
The name appears as "Viktor is a"
@Snkz @jmwohl

**Comment by Snkz** [comment]
![viktor](https://cloud.githubusercontent.com/assets/788607/6588579/0d452656-c76a-11e4-92f7-a710bd978978.jpg)

Nice troll viktor

**Comment by vr2262** [comment]
...? It seriously wasn't working. I'll grab a screenshot.

**Comment by jmwohl** [comment]
The system rejects facility names which disparage oneself. Disparaging
others is fine.

On Tue, Mar 10, 2015 at 9:45 PM, Viktor Roytman notifications@github.com
wrote:

> ...? It seriously wasn't working. I'll grab a screenshot.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SEL-Columbia/Revisit/issues/1#issuecomment-78185365.

## 

+++
608-772-9645
jonathanwohl.com
@jonwohl

**Comment by vr2262** [comment]
![untitled](https://cloud.githubusercontent.com/assets/2337403/6589090/1cc7a340-c771-11e4-926e-8cf9d39637a9.png)

**Comment by vr2262** [comment]
@Snkz @jmwohl 
Is this just Dokomoforms cutting off the text?

**Comment by Snkz** [comment]
![wp_ss_20150310_0001](https://cloud.githubusercontent.com/assets/788607/6589821/1ea8258e-c77d-11e4-91ed-a18acb772173.jpg)

I can't reproduce this even on WP dude

**Comment by vr2262** [comment]
...? Androoooooooid

**Comment by Snkz** [comment]
it must be the disparage thing jon set up
